Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -43,8 +43,12 @@ jobs:
           PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          PULUMI_LOG_LEVEL: debug  # Enable debug logging
         run: |
-          pulumi preview || echo "Pulumi preview failed. Skipping deployment." && exit 1
+          if ! pulumi preview; then
+            echo "Pulumi preview failed. Skipping deployment."
+            exit 1
+          fi
 
       - name: Pulumi Up
         env:
